{
 "title": "Central and West Clusters",
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service1",
    "label": "Service",
    "query": "label_values(destination_service)"
   },
   {
    "name": "srcns1",
    "label": "Client Workload Namespace",
    "query": "query_result( sum(istio_requests_total{reporter=\"destination\", destination_service=\"$service1\"}) by (source_workload_namespace) or sum(istio_tcp_sent_bytes_total{reporter=\"destination\", destination_service=~\"$service1\"}) by (source_workload_namespace))"
   },
   {
    "name": "srcwl1",
    "label": "Client Workload",
    "query": "query_result( sum(istio_requests_total{reporter=\"destination\", destination_service=~\"$service1\", source_workload_namespace=~\"$srcns1\"}) by (source_workload) or sum(istio_tcp_sent_bytes_total{reporter=\"destination\", destination_service=~\"$service1\", source_workload_namespace=~\"$srcns1\"}) by (source_workload))"
   },
   {
    "name": "dstns1",
    "label": "Service Workload Namespace",
    "query": "query_result( sum(istio_requests_total{reporter=\"destination\", destination_service=\"$service1\"}) by (destination_workload_namespace) or sum(istio_tcp_sent_bytes_total{reporter=\"destination\", destination_service=~\"$service1\"}) by (destination_workload_namespace))"
   },
   {
    "name": "dstwl1",
    "label": "Service Workload",
    "query": "query_result( sum(istio_requests_total{reporter=\"destination\", destination_service=~\"$service1\", destination_workload_namespace=~\"$dstns1\"}) by (destination_workload) or sum(istio_tcp_sent_bytes_total{reporter=\"destination\", destination_service=~\"$service1\", destination_workload_namespace=~\"$dstns1\"}) by (destination_workload))"
   },
   {
    "name": "service2",
    "label": "Service",
    "query": "label_values(destination_service)"
   },
   {
    "name": "srcns2",
    "label": "Client Workload Namespace",
    "query": "query_result( sum(istio_requests_total{reporter=\"destination\", destination_service=\"$service2\"}) by (source_workload_namespace) or sum(istio_tcp_sent_bytes_total{reporter=\"destination\", destination_service=~\"$service2\"}) by (source_workload_namespace))"
   },
   {
    "name": "srcwl2",
    "label": "Client Workload",
    "query": "query_result( sum(istio_requests_total{reporter=\"destination\", destination_service=~\"$service2\", source_workload_namespace=~\"$srcns2\"}) by (source_workload) or sum(istio_tcp_sent_bytes_total{reporter=\"destination\", destination_service=~\"$service2\", source_workload_namespace=~\"$srcns2\"}) by (source_workload))"
   },
   {
    "name": "dstns2",
    "label": "Service Workload Namespace",
    "query": "query_result( sum(istio_requests_total{reporter=\"destination\", destination_service=\"$service2\"}) by (destination_workload_namespace) or sum(istio_tcp_sent_bytes_total{reporter=\"destination\", destination_service=~\"$service2\"}) by (destination_workload_namespace))"
   },
   {
    "name": "dstwl2",
    "label": "Service Workload",
    "query": "query_result( sum(istio_requests_total{reporter=\"destination\", destination_service=~\"$service2\", destination_workload_namespace=~\"$dstns2\"}) by (destination_workload) or sum(istio_tcp_sent_bytes_total{reporter=\"destination\", destination_service=~\"$service2\", destination_workload_namespace=~\"$dstns2\"}) by (destination_workload))"
   }
  ]
 },
 "panels": [
  {
   "title": "West - Client Request Volume",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(rate(istio_requests_total{reporter=\"source\",destination_service=~\"$service2\"}[30s])), 0.001)"
    }
   ]
  },
  {
   "title": "West - Client Success Rate (non-5xx responses)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"source\",destination_service=~\"$service2\",response_code!~\"5.*\"}[30s])) / sum(irate(istio_requests_total{reporter=\"source\",destination_service=~\"$service2\"}[30s]))"
    }
   ]
  },
  {
   "title": "Central - Client Request Volume",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(rate(istio_requests_total{reporter=\"source\",destination_service=~\"$service1\"}[30s])), 0.001)"
    }
   ]
  },
  {
   "title": "Central - Client Success Rate (non-5xx responses)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"source\",destination_service=~\"$service1\",response_code!~\"5.*\"}[30s])) / sum(irate(istio_requests_total{reporter=\"source\",destination_service=~\"$service1\"}[30s]))"
    }
   ]
  },
  {
   "title": "West - Server Request Volume",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(rate(istio_requests_total{reporter=\"destination\",destination_service=~\"$service2\"}[30s])), 0.001)"
    }
   ]
  },
  {
   "title": "West - Server Request Volume",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(rate(istio_requests_total{reporter=\"destination\",destination_service=~\"$service2\"}[30s])), 0.001)"
    }
   ]
  },
  {
   "title": "Central - Server Request Volume",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(rate(istio_requests_total{reporter=\"destination\",destination_service=~\"$service1\"}[30s])), 0.001)"
    }
   ]
  },
  {
   "title": "Central - Server Success Rate (non-5xx responses)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"destination\",destination_service=~\"$service1\",response_code!~\"5.*\"}[30s])) / sum(irate(istio_requests_total{reporter=\"destination\",destination_service=~\"$service1\"}[30s]))"
    }
   ]
  },
  {
   "title": "West - Incoming Requests by Source And Response Code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy=\"mutual_tls\",destination_service=~\"$service2\",reporter=\"source\",source_workload=~\"$srcwl2\",source_workload_namespace=~\"$srcns2\"}[30s])) by (source_workload, source_workload_namespace, response_code), 0.001)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} : {{ response_code }} (🔐mTLS)"
    },
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy!=\"mutual_tls\", destination_service=~\"$service2\", reporter=\"source\", source_workload=~\"$srcwl2\", source_workload_namespace=~\"$srcns2\"}[30s])) by (source_workload, source_workload_namespace, response_code), 0.001)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} : {{ response_code }}"
    }
   ]
  },
  {
   "title": "Central - Incoming Requests by Source And Response Code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy=\"mutual_tls\",destination_service=~\"$service1\",reporter=\"source\",source_workload=~\"$srcwl1\",source_workload_namespace=~\"$srcns1\"}[30s])) by (source_workload, source_workload_namespace, response_code), 0.001)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} : {{ response_code }} (🔐mTLS)"
    },
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy!=\"mutual_tls\", destination_service=~\"$service1\", reporter=\"source\", source_workload=~\"$srcwl1\", source_workload_namespace=~\"$srcns1\"}[30s])) by (source_workload, source_workload_namespace, response_code), 0.001)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} : {{ response_code }}"
    }
   ]
  },
  {
   "title": "West - Incoming Request by Destination and Response Code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy=\"mutual_tls\",destination_service=~\"$service2\",reporter=\"destination\",destination_workload=~\"$dstwl2\",destination_workload_namespace=~\"$dstns2\"}[30s])) by (destination_workload, destination_workload_namespace, response_code), 0.001)",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} : {{ response_code }} (🔐mTLS)"
    },
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy!=\"mutual_tls\", destination_service=~\"$service2\", reporter=\"destination\", destination_workload=~\"$dstwl2\", destination_workload_namespace=~\"$dstns2\"}[30s])) by (destination_workload, destination_workload_namespace, response_code), 0.001)",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} : {{ response_code }}"
    }
   ]
  },
  {
   "title": "Central - Incoming Request by Destination and Response Code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy=\"mutual_tls\",destination_service=~\"$service1\",reporter=\"destination\",destination_workload=~\"$dstwl1\",destination_workload_namespace=~\"$dstns1\"}[30s])) by (destination_workload, destination_workload_namespace, response_code), 0.001)",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} : {{ response_code }} (🔐mTLS)"
    },
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy!=\"mutual_tls\", destination_service=~\"$service1\", reporter=\"destination\", destination_workload=~\"$dstwl1\", destination_workload_namespace=~\"$dstns1\"}[30s])) by (destination_workload, destination_workload_namespace, response_code), 0.001)",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }} : {{ response_code }}"
    }
   ]
  },
  {
   "title": "West - Client Request Duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\",destination_service=~\"$service2\"}[1m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\",destination_service=~\"$service2\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\",destination_service=~\"$service2\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "West - Server Request Duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_service=~\"$service2\"}[1m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_service=~\"$service2\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_service=~\"$service2\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Central - Client Request Duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\",destination_service=~\"$service1\"}[1m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\",destination_service=~\"$service1\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"source\",destination_service=~\"$service1\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Central - Server Request Duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_service=~\"$service1\"}[1m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_service=~\"$service1\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_service=~\"$service1\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  }
 ]
}